output_dir: "./outputs/fixed-inbalanced-target-correct-experts"
seed: null

target:
  type: model  # "piecewise_linear" or "model"
  domain: [-1, 1]
  kwargs:
    num_experts: 4
    input_dim: 1
    output_dim: 1
    router_top_k: 2
    initial_expert_weights:
      - [[2.0]]
      - [[-1.0]]
      - [[3.0]]
      - [[-4.0]]
    initial_expert_biases:
      - [2.0]
      - [-1.0]
      - [0.0]
      - [3.0]
    initial_gating_weights:
      - [-1.0]
      - [-0.5]
      - [0.5]
      - [4.0]
    initial_gating_biases: 
      - -0.40
      - -0.00
      - -0.25
      - -2.6

model:
  num_experts: 4
  input_dim: 1
  output_dim: 1
  router_top_k: 2
  freeze_router: false
  freeze_experts: true
  initial_expert_weights:
    - [[2.0]]
    - [[-1.0]]
    - [[3.0]]
    - [[-4.0]]
  initial_expert_biases:
    - [2.0]
    - [-1.0]
    - [0.0]
    - [3.0]
  initial_gating_weights:
    - [-0.5]
    - [-0.0]
    - [0.25]
    - [0.5]
  initial_gating_biases: 
    - -0.25
    - -0.5
    - -0.1
    - -0.4

training:
  num_steps: 500
  batch_size: 100
  learning_rate: 0.01
  # Controls the weight of the Switch Transformer-style load balancing loss (1e-2 default from paper).
  load_balancing_loss_weight: 0.0
  # DeepSeek V3 auxiliary loss-free load balancing gamma, controlling how much is added/subtracted to under/over-utilized experts (1e-3 default from paper)
  auxiliarly_loss_free_load_balancing_gamma: 0.0

logging:
  anim_sampling_rate: 1

wandb:
  enabled: true
  project: moe-shaping
  entity: mari-schn
  run_name: fixed-inbalanced-target-correct-experts
  run_tags: []
